#! /usr/bin/env zsh

dockerup () {
	mkdir -p ~/.docker/cli-plugins

	docker_url=https://download.docker.com/mac/static/stable/x86_64
	docker_version=18.06.3-ce
	curl -fsSL $docker_url/docker-$docker_version.tgz | \
	tar zxvf - --strip 1 -C ~/.docker/ docker/docker

	compose_url=https://github.com/docker/compose/releases/download/v2.1.0/docker-compose-darwin-x86_64
	curl -fsSL $compose_url >! ~/.docker/cli-plugins/docker-compose
	chmod +x ~/.docker/cli-plugins/docker-compose
}

dockerup "$@"
