#! /usr/bin/env zsh

local -a repos
repos=()

_zed_git() {
  local repo=${1:t}
  local dir=$ZDOTDIR/$repo
  repos=($repos $repo)
}

_zed_ls() {
  for ((i = 1; i <= $#repos; i++)) print -r -- $repos[i]
}

_zed_up() {
  for ((i = 1; i <= $#repos; i++)) {
    print -r -- $repos[i]
    local repo=$repos[i]
    local dir=$ZDOTDIR/$repo
    git -C $ZDOTDIR submodule add --force $1 $dir
  }
  git -C $ZDOTDIR submodule update --recursive --remote
  git -C $ZDOTDIR maintenance start
  # autoload -Uz zcompile
  # zcompile $ZDOTDIR/.zshrc
}

_zed_help() {
  print -r -- "Usage: zed git https://github.com/USERNAME/REPO"
  return 1
}

zed() {
  case "$1" in
    git)  _zed_git  ${@:2};;
    ls)   _zed_ls   ${@:2};;
    up)   _zed_up   ${@:2};;
    *)    _zed_help ${@:2};;
  esac
}
