#! /usr/bin/env zsh

zinit() {
	local zcache=${ZSH_CACHE:-${XDG_CACHE_HOME:-~/.cache}/zsh}
  local zinit="$zcache/zinit.zsh"
  local zcd="${ZCOMPDUMP:-$zcache/.zcompdump}"

  autoload -Uz compinit

  if [[ ! -f $zinit || $1 == 'force' ]]; then
    mkdir -p ${zinit:h}
    _zinit >! $zinit
    compinit -i -d $zcd
    zcompile $zcd $zinit
  fi

  compinit -C -d $zcd
  source $zinit
}

zinit "$@"
